### ISSUE TITLE
toml.decoder.TomlDecodeError: Key group not on a line by itself. (line 1 column 1 char 0)

### ISSUE THREAD

**Issue by LvShuaiChao** [liuyixin-louis/arxiv2latex#1]
Hello, the description of this project is great, but I found that the main function cannot run normally in the actual use process
![image](https://user-images.githubusercontent.com/35528109/202473698-d2c15dd7-de20-4dd5-bc6e-2c603aa8cef1.png)

**Comment by liuyixin-louis** [comment]
please check the version of st.
